# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_ip', models.CharField(max_length=45)),
                ('chip_num', models.CharField(max_length=8)),
                ('chip_oper', models.CharField(max_length=15)),
                ('chip_data', models.CharField(max_length=17)),
                ('chip_where', models.CharField(default='0', max_length=1)),
                ('chip_whedes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChipSaidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.IntegerField(default=0)),
                ('chip_data', models.CharField(max_length=17)),
                ('saida_autorz', models.CharField(max_length=45)),
                ('saida_para', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryChip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.IntegerField(default=0)),
                ('hora', models.CharField(max_length=17)),
                ('event', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ids', models.IntegerField(default=0)),
                ('hora', models.CharField(max_length=17)),
                ('event', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sessionini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ids', models.IntegerField(default=0)),
                ('token', models.CharField(max_length=64)),
                ('user_tipe', models.CharField(max_length=1)),
                ('ativo', models.BooleanField(default=False)),
                ('horaini', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nome', models.CharField(max_length=45)),
                ('user_pass', models.CharField(max_length=32)),
                ('user_tipe', models.CharField(max_length=1)),
                ('user_ativo', models.CharField(default='s', max_length=1)),
            ],
        ),
    ]
