# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='chip_ativo',
            field=models.CharField(default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='chip',
            name='chip_where',
            field=models.CharField(default='e', max_length=1),
        ),
    ]
