# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
