# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180807_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.IntegerField(default=0)),
                ('chip_data', models.CharField(max_length=17)),
                ('entradapor', models.CharField(max_length=45)),
                ('event', models.CharField(max_length=100)),
            ],
        ),
    ]
