# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_session_horaini'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessionini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('token', models.CharField(max_length=64)),
                ('user_tipe', models.CharField(max_length=1)),
                ('ativo', models.BooleanField(default=False)),
                ('horaini', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
