# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180718_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionini',
            old_name='user_id',
            new_name='user_ids',
        ),
    ]
