# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180718_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ids', models.IntegerField(default=0)),
                ('hora', models.CharField(max_length=17)),
                ('event', models.CharField(max_length=100)),
            ],
        ),
    ]
